Enhancements in Track Handling and Artist Recognition for Yandex Music
topi314/LavaSrc pull request #134
Opened 2023-10-24 20:12 UTC by BrokenFG

Added support for manually uploaded tracks (only those uploaded by the token owner available)

Implemented recognition of track links without specifying the album, e.g., https://music.yandex.ru/track/75370207

Now, if a track has multiple artists, all of them will be listed in the author field instead of just one.

2023-10-24 23:17 UTC, topi314 commented
@AgutinVBoy any chance you can check this out?

2023-10-25 03:13 UTC, AgutinVBoy commented
> @AgutinVBoy any chance you can check this out?

Ok. In the day.

2023-10-25 11:38 UTC, AgutinVBoy requested changes

2023-10-25 11:38 UTC, AgutinVBoy commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +	public static final Pattern URL_TRACK_PATTERN = Pattern.compile("(https?://)?music\\.yandex\\.(ru|com)/(?<type1>track)/(?<identifier>[0-9]+)");
```suggestion
	public static final Pattern URL_TRACK_PATTERN = Pattern.compile("(https?://)?music\\.yandex\\.(ru|com)/(?<type1>track)/(?<identifier>[0-9a-z-]+)");
```
Custom tracks have a different identifier pattern.

2023-10-25 11:38 UTC, AgutinVBoy commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> -		if (!json.get("available").asBoolean(false) || json.get("albums").values().isEmpty()) {
@topi314, I'm not sure if `json.get("albums").values().isEmpty()` needs to be removed. It's not my improvement.

2023-10-25 11:55 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> -		if (!json.get("available").asBoolean(false) || json.get("albums").values().isEmpty()) {
this can be removed then I think
it came from this pr https://github.com/topi314/LavaSrc/pull/31

2023-10-25 11:57 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +	public static final Pattern URL_TRACK_PATTERN = Pattern.compile("(https?://)?music\\.yandex\\.(ru|com)/(?<type1>track)/(?<identifier>[0-9]+)");
cant we fit this regex into the one above?

2023-10-25 12:15 UTC, AgutinVBoy commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +	public static final Pattern URL_TRACK_PATTERN = Pattern.compile("(https?://)?music\\.yandex\\.(ru|com)/(?<type1>track)/(?<identifier>[0-9]+)");
Technically yes, but the regular expression will become less stable. (Official tracks only `0-9`; custom: `a-z0-9-`

My opinion: adding local tracks (which can only be enabled by the token owner) should not be added to the global release. Alternatively, it's worth adding a toggle in the config.

2023-10-25 12:51 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +	public static final Pattern URL_TRACK_PATTERN = Pattern.compile("(https?://)?music\\.yandex\\.(ru|com)/(?<type1>track)/(?<identifier>[0-9]+)");
I'm fine with having a toggle, but then we also need to filter them from playlists

2023-10-25 16:07 UTC, BrokenFG commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +	public static final Pattern URL_TRACK_PATTERN = Pattern.compile("(https?://)?music\\.yandex\\.(ru|com)/(?<type1>track)/(?<identifier>[0-9]+)");
I don't think anyone will use the track URL for local tracks, I'm only adding this because tracks should be recognized without mentioning the album

Without proper knowledge, the user will not be able to get the ID of the local track, and again, even if he gets it, the track can only be played if it was uploaded by the token owner. The main purpose of this improvement is that owners of private bots can create their own playlists, where they might like to be able to upload tracks that are not in Yandex music and be able to listen to them through the bot. I don't think that some kind of switch is needed for this functionality

2023-10-25 16:29 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +	public static final Pattern URL_TRACK_PATTERN = Pattern.compile("(https?://)?music\\.yandex\\.(ru|com)/(?<type1>track)/(?<identifier>[0-9]+)");
What you say then

2023-10-25 18:01 UTC, BrokenFG commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +	public static final Pattern URL_TRACK_PATTERN = Pattern.compile("(https?://)?music\\.yandex\\.(ru|com)/(?<type1>track)/(?<identifier>[0-9]+)");
Yeah, we can combine them

2023-10-25 20:58 UTC, AgutinVBoy commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +	public static final Pattern URL_TRACK_PATTERN = Pattern.compile("(https?://)?music\\.yandex\\.(ru|com)/(?<type1>track)/(?<identifier>[0-9]+)");
> Without proper knowledge, the user will not be able to get the ID of the local track, and again. 

Some bots do this: `[song title](link to song)`. In this case there will be a valid link to the private track.
And then anyone can use that link (in a specific bot) until the track is deleted.

2023-10-25 21:16 UTC, BrokenFG commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +	public static final Pattern URL_TRACK_PATTERN = Pattern.compile("(https?://)?music\\.yandex\\.(ru|com)/(?<type1>track)/(?<identifier>[0-9]+)");
So, we want to be able to play private tracks using their url or not?

2023-10-26 16:19 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +	public static final Pattern URL_TRACK_PATTERN = Pattern.compile("(https?://)?music\\.yandex\\.(ru|com)/(?<type1>track)/(?<identifier>[0-9]+)");
I dont use yandex, so u both should come to a conclusion

2023-10-26 21:43 UTC, BrokenFG commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +	public static final Pattern URL_TRACK_PATTERN = Pattern.compile("(https?://)?music\\.yandex\\.(ru|com)/(?<type1>track)/(?<identifier>[0-9]+)");
@topi314 I think the decision is yours, my opinion is that private tracks should not be recognized

2023-10-27 18:56 UTC, AgutinVBoy commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +	public static final Pattern URL_TRACK_PATTERN = Pattern.compile("(https?://)?music\\.yandex\\.(ru|com)/(?<type1>track)/(?<identifier>[0-9]+)");
Okay, let's keep the private tracks... private :)

2023-12-10 18:43 UTC, topi314 commented
is this done? or what is the current status on this?
you never asked us to review again

2024-01-23 13:58 UTC, BrokenFG commented
@topi314 Sorry, was on vacation. Yes, its done in my understanding

2024-01-23 14:10 UTC, topi314 commented
your branch is 11 commits behind master, can you please first merge before I take a look?
https://github.com/BrokenFG/LavaSrc/compare/master...topi314%3ALavaSrc%3Amaster

2024-01-23 14:44 UTC, BrokenFG commented
Done

2024-01-23 22:10 UTC, topi314 requested changes
please also update the supported links in the readme https://github.com/topi314/LavaSrc#yandex-music-1

2024-01-23 22:10 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +	}
this is some cursed code
```suggestion
	private List<JsonBrowser> getTracks(String trackIds) throws IOException {
		return getJson(PUBLIC_API_BASE + "/tracks?track-ids=" + URLEncoder.encode(trackIds, StandardCharsets.UTF_8)).get("result").values();
	}
```

this gets rid off like 3 other fucntions

2024-02-09 10:34 UTC, BrokenFG commented
done

2024-02-17 19:05 UTC, topi314 requested changes

2024-02-17 19:05 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +		} catch (IOException | URISyntaxException e) {
```suggestion
		} catch (IOException e) {
```

2024-02-17 19:05 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +
```suggestion
```
this has no usages

2024-02-17 19:05 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +
```suggestion
```
this has no usages

2024-02-17 19:05 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +	public JsonBrowser getJson(URI uri) throws IOException {
why does this overload exist?
there is only one usage by `public JsonBrowser getJson(String uri) throws IOException {`

2024-02-22 18:18 UTC, BrokenFG commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +	public JsonBrowser getJson(URI uri) throws IOException {
this overload exists for methods that was removed by your suggestion (buildUriWithParams). Can delete it now

2024-03-05 08:50 UTC, topi314 approved these changes

2024-03-10 18:04 UTC, merged

2024-03-10 18:05 UTC, topi314 commented
alright thanks for the contribution
sorry that it took another 5 days to merge