Fix ReadMe incorrect imports
topi314/LavaSrc pull request #145
Opened 2023-11-23 03:54 UTC by Jacrispys

The maven and gradle imports had lavasrc-protocol instead of lavasrc-plugin, as well as maven didn't have a id for repository.

2023-11-23 07:29 UTC, topi314 commented
not sure why the plugin would be of any relevance for lavaplayer

2023-11-23 07:31 UTC, Jacrispys commented
not sure if plugin is the correct import, i just saw that there were only 2 items within the repo (lavasrc, and lavasrc-plugin) so i assumed the name had changed from protocol to plugin for some reason.

2023-11-23 07:55 UTC, topi314 commented
there has just not been a release yet with the protocol module, its there because I was too lazy to create a new readme entry for lavalink with jvm clients

2023-11-26 16:04 UTC, topi314 requested changes
then I can merge it

2023-11-26 16:04 UTC, topi314 commented on README.md
> +  implementation "com.github.topi314.lavasrc:lavasrc-plugin:x.y.z"
```suggestion
  implementation "com.github.topi314.lavasrc:lavasrc-protocol:x.y.z"
```

2023-11-26 16:04 UTC, topi314 commented on README.md
> +      <artifactId>lavasrc-plugin</artifactId>
```suggestion
      <artifactId>lavasrc-protocol</artifactId>
```

2023-11-26 16:05 UTC, topi314 approved these changes

2023-11-26 16:05 UTC, merged