LavaSrc fix Yandex Music playlist and artist's track limit
topi314/LavaSrc pull request #155
Opened 2023-12-30 12:14 UTC by llimonix

I checked on different playlists that caused errors, it works correctly

2024-01-01 11:12 UTC, topi314 requested changes

2024-01-01 11:12 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +					var trackIdsStr = String.join("%2C", trackIds);
please properly url encode this instead of simply joining with `%2C`
You can also do this using a stream

2024-01-01 11:12 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +			if (playlistTracks.size() != 0) {
please use early returns, avoid `if else` if possible
```java
if (playlistTracks.size() == 0) {
	return AudioReference.NO_TRACK;
}
```

you can also already return by checking the length of `json.get("result").get("tracks").values()`

2024-01-01 11:12 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +				int chunkSize = 300;
make this a constant

2024-01-01 21:40 UTC, topi314 requested changes
the lavaplayer api does not support returning playlists, albums or artists in search results, so it makes no sense to return them here

that being said, [LavaSearch](https://github.com/topi314/LavaSearch) does support this so please implement this for LavaSearch instead if you want this feature
You can checkout Deezer, Spotify, YT or Apple Music for an example implementation

2024-01-01 21:40 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +				return this.getPlaylist(userId, playlistId);
this makes no sense, we don't resolve playlists while searching
we only provide a list of tracks

2024-01-01 21:40 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +				return this.getArtist(artistId);
this makes no sense, we don't resolve playlists while searching
we only provide a list of tracks

2024-01-01 21:40 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +				return this.getAlbum(albumId);
this makes no sense, we don't resolve playlists while searching
we only provide a list of tracks

2024-01-02 16:58 UTC, llimonix commented
I rolled back the solutions with the search for more than just tracks. Since I did not understand how to implement it correctly in order to transmit it in the correct format. 

My solution works and searches for the best match for a text query. But as I understand it, you need to get a track list from the best result, if it is a playlist/album/artist, and pass it to return new BasicAudioPlaylist("Yandex Music Search: " + query, tracks, null, true);

But, alas. It is not yet clear how to do this

2024-01-03 00:36 UTC, topi314 requested changes
for the extended search functionality via LavaSearch you have to implement the `AudioSearchManager` interface in the `YandexMusicSourceManager`.
You can check this here for deezer as an example https://github.com/topi314/LavaSrc/blob/master/main/src/main/java/com/github/topi314/lavasrc/deezer/DeezerAudioSourceManager.java#L83

2024-01-03 00:36 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +				int endIndex = Math.min(i + 300, playlistTracks.size());
this is still not a constant

2024-01-03 00:36 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +				.collect(Collectors.joining(","));
```suggestion
				String trackIdsStr = trackIds.stream().collect(Collectors.joining(","));
```

2024-01-03 00:36 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +
```suggestion

```

2024-01-03 00:36 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +		if (json == null || json.isNull() || !json.get("error").isNull() || json.get("result").values().get(0).get("available").text().equals("false")) {
instead of returning `AudioReference.NO_TRACK` on error we should throw an exception

2024-01-03 00:36 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +		if (json == null || json.isNull() || !json.get("error").isNull() || json.get("result").values().isEmpty()) {
here too

2024-01-03 00:36 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +		if (json == null || json.isNull() || !json.get("error").isNull() || json.get("result").isNull()) {
here too

2024-01-03 00:36 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +		if (json == null || json.isNull() || !json.get("error").isNull() || json.get("result").get("tracks").isNull()) {
here too

2024-01-03 00:36 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +		if (json == null || json.isNull() || !json.get("error").isNull() || json.get("result").isNull() || json.get("result").get("tracks").values().isEmpty()) {
here too

2024-01-03 01:53 UTC, llimonix commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +		if (json == null || json.isNull() || !json.get("error").isNull() || json.get("result").isNull() || json.get("result").get("tracks").values().isEmpty()) {
I didn't understand anything. I've only added json == null here and !json.get("error").isNull()

Since sometimes the response comes without json and json.isNull() returns an error

2024-01-03 07:44 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +		if (json == null || json.isNull() || !json.get("error").isNull() || json.get("result").isNull() || json.get("result").get("tracks").values().isEmpty()) {
if you already check for an error response here `!json.get("error").isNull()` then you might as well throw an error when we get those.
silently returning no track on error would be kinda bad
before it would run into the code below and throw an error there since the other json props are missing, but this isnt the case anymore

2024-01-03 19:08 UTC, llimonix commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +		if (json == null || json.isNull() || !json.get("error").isNull() || json.get("result").isNull() || json.get("result").get("tracks").values().isEmpty()) {
Show an example of how to fix it

2024-01-03 19:41 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +		if (json == null || json.isNull() || !json.get("error").isNull() || json.get("result").isNull() || json.get("result").get("tracks").values().isEmpty()) {
https://github.com/topi314/LavaSrc/blob/master/main/src/main/java/com/github/topi314/lavasrc/deezer/DeezerAudioTrack.java#L68

2024-02-17 19:06 UTC, topi314 commented
do you still want this or can I close it?

2024-02-18 01:32 UTC, llimonix commented
> do you still want this or can I close it?

I understand that I have errors in the correctness of writing the code. I do not know how to fix them so that everything fits you. 

I compiled everything for myself, there were no problems. I'm too lazy to think about how to fix it.

The error on your part has not been resolved, and playlists remain that simply do not work.

Close it

2024-02-18 14:39 UTC, topi314 commented
the main issue is the error handling
you are returning no track found if there is an error in the response which is not good since we wouldnt know if an error happened
you can make a similar method to this in deezer to check for errors in responses which would throw an appropriate error https://github.com/topi314/LavaSrc/blob/master/main/src/main/java/com/github/topi314/lavasrc/deezer/DeezerAudioTrack.java#L68

2024-02-18 16:11 UTC, llimonix commented
> the main issue is the error handling you are returning no track found if there is an error in the response which is not good since we wouldnt know if an error happened you can make a similar method to this in deezer to check for errors in responses which would throw an appropriate error https://github.com/topi314/LavaSrc/blob/master/main/src/main/java/com/github/topi314/lavasrc/deezer/DeezerAudioTrack.java#L68

if I leave what was before my changes, will it be wrong too?

if (json.isNull() || json.get("result").isNull())
if (json.isNull() || json.get("result").isNull() || json.get("result").get("tracks").values().isEmpty())

And so on

2024-05-16 21:09 UTC, topi314 commented
is this still relevant after https://github.com/topi314/LavaSrc/pull/197?

2024-05-16 23:47 UTC, closed without merging