Added LavaSrc pluginInfo for yandex music tracks
topi314/LavaSrc pull request #191
Opened 2024-05-10 20:47 UTC by Krispeckt

2024-05-10 20:54 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +			null,
Are those guaranteed to be there on every endpoint/response?

If not those should be nullable

2024-05-10 20:59 UTC, Krispeckt commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +			null,
Я использую плагин уже довольно давно, по крайней мере, я не замечал этого, но я могу это исправить.

2024-05-10 21:52 UTC, Krispeckt commented
Fixed it

2024-05-13 17:55 UTC, topi314 requested changes
while you are at it are you also interested in adding the `ExtendedAudioPlaylist` stuff?
this is not a requirement tho

2024-05-13 17:55 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicAudioTrack.java
> +	public YandexMusicAudioTrack(AudioTrackInfo trackInfo, String albumName, String albumUrl, String artistUrl, String artistArtworkUrl, String previewUrl, YandexMusicSourceManager sourceManager) {
since `previewUrl` is always null it seems like let's remove it from the constructor too like `isPreview`

2024-05-13 17:56 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +			null,
lgtm

2024-05-14 14:03 UTC, Krispeckt commented
> while you are at it are you also interested in adding the `ExtendedAudioPlaylist` stuff? this is not a requirement tho

I don't get it, it's already implemented :/ But there were a few bugs there

2024-05-14 15:56 UTC, closed without merging