Yandex Music Lyrics
topi314/LavaSrc pull request #199
Opened 2024-05-20 10:47 UTC by Krispeckt

I thought it would take a lot longer xd

2024-05-20 20:10 UTC, topi314 requested changes
eh don't get me wrong, but your code style is rather weird

do you know how to use java lists?
also please don't use `java.net.URL`

also what format does the lyrics endpoint return? text?
is the lyrics source of yandex really musixmatch?

2024-05-20 21:18 UTC, Krispeckt commented
> eh don't get me wrong, but your code style is rather weird
not much experience with java

> do you know how to use java lists?
What do you mean?

> also what format does the lyrics endpoint return? text?
Yes

> is the lyrics source of yandex really musixmatch?
idk but the api response says yes

2024-05-20 21:23 UTC, Krispeckt commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +                }
Is it worth this code? Yandex does not support isrc because of this the wrong track may be selected

2024-05-20 21:25 UTC, topi314 commented
do you have an example response for me to look at?

2024-05-20 21:26 UTC, topi314 commented
> > do you know how to use java lists?

> What do you mean?


you always seem to call `someList.toArray()` which is not really what you should do
use lists they are nice

2024-05-20 21:45 UTC, topi314 commented
ah okay, now your code makes more sense lol

2024-05-20 21:47 UTC, Krispeckt commented
> ah okay, now your code makes more sense lol

what exactly is your problem? I realized my mistakes
xd

2024-05-20 21:48 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +                }
its certainly not ideal, but kinda the best shot we have
what you can do is compare them more closely if this should become an issue

2024-05-20 21:50 UTC, topi314 commented
I was just trying to find out what this code actually does and why you need some regex 💀
but with the format of the returned lyrics it makes more sense.

Is there really no way to get a json response from that endpoint?

2024-05-20 21:54 UTC, Krispeckt commented
> I was just trying to find out what this code actually does and why you need some regex 💀 but with the format of the returned lyrics it makes more sense.
> 
> Is there really no way to get a json response from that endpoint?

Idk, yandex amazing service. In all other api's there is no other way, nor is there any other way in the docs

2024-05-20 21:54 UTC, topi314 commented
it looks okay for now, I'll give it a propper review later since it's getting late 👍🏻

2024-05-20 21:56 UTC, Krispeckt commented
> it looks okay for now, I'll give it a propper review later since it's getting late 👍🏻

Can you also reformat the code with normal indents? My intellij is going crazy

2024-05-23 19:31 UTC, topi314 commented
never used `Number`
thanks 💀

2024-05-23 20:07 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +			"https://music.yandex.ru/artist/" + id,
shouldn't this also have the `domainEnd`?

2024-05-23 20:08 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +			"Yandex Music Recommendations For Track: " + trackInfo.get("title").text(),
I don't think we include the recommendation title anywhere usually. Should we make the naming consistent?

2024-05-23 20:11 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +				Duration.ofMillis(Math.max(nextTimestamp.toMillis() - lyricsLine.getTimestamp().toMillis(), 0)),
I don't think we should calculate the duration here, it's optional in the `LavaLyrics` api, some providers return it, and some simply not

it's not accurate anyway

2024-05-24 06:52 UTC, Krispeckt commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +				Duration.ofMillis(Math.max(nextTimestamp.toMillis() - lyricsLine.getTimestamp().toMillis(), 0)),
I would leave that code in, as it wouldn't be redundant

2024-05-24 09:29 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +				Duration.ofMillis(Math.max(nextTimestamp.toMillis() - lyricsLine.getTimestamp().toMillis(), 0)),
the thing is, a line might be shorter than the duration between the timestamps, it might be inaccurate

2024-05-24 09:58 UTC, Krispeckt commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +				Duration.ofMillis(Math.max(nextTimestamp.toMillis() - lyricsLine.getTimestamp().toMillis(), 0)),
No argue, but in some moments Yandex gives blank lines, letting i know that it starts an empty moment in the track. As if you can leave that logic until the first issue :>

2024-05-24 11:03 UTC, topi314 approved these changes

2024-05-24 11:03 UTC, merged

2024-05-24 11:05 UTC, topi314 commented
thanks