Implement Yandex Music LavaSearch and few fixes
topi314/LavaSrc pull request #200
Opened 2024-05-24 21:33 UTC by Krispeckt

Personally, I have no idea how to compare more thoroughly, if you do, I can redo it :/ But again, my opinion is better to remove this [logic](https://github.com/topi314/LavaSrc/blob/master/main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java#L101-L113).

2024-05-28 13:35 UTC, Krispeckt commented
where's my review 🥹

2024-05-31 12:48 UTC, topi314 requested changes
I recently made it so you can toggle lyrics for sources. This is missing in here: https://github.com/topi314/LavaSrc/commit/f154ce1999b173bc9a0715128ef3cfb6ed73c453

2024-05-31 13:12 UTC, Krispeckt commented
> I recently made it so you can toggle lyrics for sources. This is missing in here: https://github.com/topi314/LavaSrc/commit/f154ce1999b173bc9a0715128ef3cfb6ed73c453

It's already been done, lul

2024-05-31 13:29 UTC, topi314 commented
Perhaps I should have slept more 💀

2024-05-31 13:34 UTC, topi314 commented
You did forget to check for it in here https://github.com/Krispeckt/LavaSrc/blob/master/plugin%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgithub%2Ftopi314%2Flavasrc%2Fplugin%2FLavaSrcPlugin.java#L62

2024-06-03 20:01 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +		}
now thinking about it, it would prob be better to just ignore unsupported `AudioSearchResult` types
this would need to be changed in deezer too ig

2024-06-03 20:03 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +						}
let's omit this for now
I have a different change planned for this

2024-06-03 20:05 UTC, Krispeckt commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +						}
Is there any way to keep this as a temporary solution?

2024-06-04 16:33 UTC, Krispeckt commented
As if using warnings would be a better solution

2024-06-04 17:26 UTC, topi314 commented
just remove the checks completely

2024-06-05 11:00 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +						}
not needed, I should have the other stuff ready in the next days

2024-06-05 12:40 UTC, Krispeckt commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +						}
I need to remove it, right?

2024-06-05 12:48 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/yandexmusic/YandexMusicSourceManager.java
> +						}
yes

2024-06-05 15:40 UTC, Krispeckt commented
Done

2024-06-09 21:21 UTC, topi314 approved these changes

2024-06-09 21:21 UTC, merged

2024-06-09 21:21 UTC, topi314 commented
thanks