Local File Support
topi314/LavaSrc pull request #206
Opened 2024-07-17 06:31 UTC by clapann

Added support for Spotify local files and included an option for this feature in the configuration.

2024-07-17 07:17 UTC, topi314 commented
while this code looks decent, what happens when you try to play a local file?

2024-07-17 07:21 UTC, clapann commented
Nothing. Me personally I handled it with my client. I sift through the playlist results, and then recorrect the tracks to a proper format by searching for it.

2024-07-17 07:25 UTC, topi314 commented
Do you have an example playlist for me to test?

2024-07-17 07:29 UTC, clapann commented
This playlists first track is a local file while the second track isn't. In total there should be 104 tracks including local files and 94 tracks excluding local files. https://open.spotify.com/playlist/5vJw9wsX5MTkhkSiY04bIw?si=7kT0rDfgQkSkzHhKcZ6tHQ

2024-07-17 08:02 UTC, topi314 commented
can you also please update the docs in the readme?

2024-07-19 17:39 UTC, topi314 requested changes

2024-07-19 17:39 UTC, topi314 commented on README.md
>  * https://open.spotify.com/playlist/7HAO9R9v203gkaPAgknOMp
```suggestion
* https://open.spotify.com/playlist/7HAO9R9v203gkaPAgknOMp (playlists can include local files if you enabled this via: `plugins.lavasrc.spotify.localFiles: true`. Please note `uri` & `iscr` will be `null` & `identifier` will be `"local"`
```

2024-07-19 17:39 UTC, topi314 commented on README.md
> +* Local files (URI and ISRC are null, and ID is set to "local" for all local files)
```suggestion
```

2024-07-19 17:39 UTC, topi314 commented on application.example.yml
> +      localFiles: false # Enable local files support with Spotify playlists. (URI and ISRC are null, and ID is set to "local" for all local files)
reword like above

2024-07-19 17:39 UTC, topi314 commented on README.md
> +      localFiles: false # Enable local files support with Spotify playlists.
reword like below

2024-07-19 17:39 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/spotify/SpotifySourceManager.java
> +						track.get("is_local").asBoolean(false) || track.get("type").text().equals("episode"))) {
I think this check could be done simpler

2024-07-19 17:39 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/spotify/SpotifySourceManager.java
> +	private AudioTrack parseTrack(JsonBrowser json, boolean preview, boolean thisLocalFiles) {
not sure why `thisLocalFiles` is needed?

2024-07-19 23:46 UTC, clapann commented on application.example.yml
> +      localFiles: false # Enable local files support with Spotify playlists. (URI and ISRC are null, and ID is set to "local" for all local files)
Done.

2024-07-19 23:46 UTC, clapann commented on main/src/main/java/com/github/topi314/lavasrc/spotify/SpotifySourceManager.java
> +						track.get("is_local").asBoolean(false) || track.get("type").text().equals("episode"))) {
Done.

2024-07-19 23:47 UTC, clapann commented on main/src/main/java/com/github/topi314/lavasrc/spotify/SpotifySourceManager.java
> +	private AudioTrack parseTrack(JsonBrowser json, boolean preview, boolean thisLocalFiles) {
Fixed.

2024-07-19 23:50 UTC, clapann commented
All changes implemented.

2024-07-20 08:36 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/spotify/SpotifySourceManager.java
> +		if(json.get("name").isNull()) {
in which case is `name` null?

2024-07-20 08:37 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/spotify/SpotifySourceManager.java
> +		String artist = Optional.ofNullable(json.get("artists").index(0).get("name").text()).orElse("local");
no need to use `Optional` here, just use ternaries

2024-07-20 20:04 UTC, clapann commented on main/src/main/java/com/github/topi314/lavasrc/spotify/SpotifySourceManager.java
> +		if(json.get("name").isNull()) {
I didn't know when local files aren't tagged correctly, it would default to file name. Fixed in newest commit.

2024-07-20 20:04 UTC, clapann commented on main/src/main/java/com/github/topi314/lavasrc/spotify/SpotifySourceManager.java
> +		String artist = Optional.ofNullable(json.get("artists").index(0).get("name").text()).orElse("local");
Done.

2024-07-20 20:04 UTC, clapann commented
All changes implemented.

2024-07-21 14:21 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/spotify/SpotifySourceManager.java
> +		String artist = json.get("artists").index(0).get("name").text() != null ? json.get("artists").index(0).get("name").text() : "local";
if no artist is given it should default to `Unknown` like in other sources

2024-07-21 19:44 UTC, clapann commented on main/src/main/java/com/github/topi314/lavasrc/spotify/SpotifySourceManager.java
> +		String artist = json.get("artists").index(0).get("name").text() != null ? json.get("artists").index(0).get("name").text() : "local";
I updated the code to check for `isEmpty()` instead of `null` for artist names, because Spotify sends an empty string when the artist name is not available.

2024-07-22 20:08 UTC, topi314 approved these changes

2024-07-22 20:08 UTC, merged

2024-07-22 20:08 UTC, topi314 commented
thanks