Implement Vk Music Source Manager 😎
topi314/LavaSrc pull request #207
Opened 2024-07-24 23:06 UTC by Krispeckt

2024-08-01 20:26 UTC, Krispeckt commented
I hope for a fairly quick review of this pr.
If you need it, here's the documentation for the music api https://vodka2.github.io/vk-audio-token/
The work done is not small, there were a lot of tests, all the bugs that were found by users are fixed.

2024-08-12 13:10 UTC, topi314 commented
since this pr seems to be active again, how long should I wait before reviewing it?

2024-08-12 13:12 UTC, Krispeckt commented
Idk 😅 but for me personally I'm all set, it's just that I've been informed that the lyric in the vk may still give it with timestamps

2024-08-20 19:58 UTC, topi314 commented
you want to rebase this pr onto master, there have been some readme changes

2024-08-20 20:11 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/vkmusic/VkMusicAudioTrack.java
> +		return new URI(json.get("response").values().get(0).get("url").text());
can there be some kind of error you should try to parse?

2024-08-20 20:13 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/vkmusic/VkMusicSourceManager.java
> +		if (userToken == null || userToken.isEmpty()) {
`userToken` can't be empty since the constructor already throws an exception

2024-08-20 20:13 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/vkmusic/VkMusicSourceManager.java
> +		if (userToken == null || userToken.isEmpty()) {
`userToken` can't be empty since the constructor already throws an exception

2024-08-20 20:16 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/vkmusic/VkMusicSourceManager.java
> +		if (userToken == null || userToken.isEmpty()) {
`userToken` can't be empty since the constructor already throws an exception

2024-08-20 20:17 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/vkmusic/VkMusicSourceManager.java
> +				throw new RuntimeException(e);
please don't throw `RuntimeExceptions` in here randomly, just add them to the method signatures and let them bubble upwards and cached there

2024-08-20 20:17 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/vkmusic/VkMusicSourceManager.java
> +		if (userToken == null || userToken.isEmpty()) {
`userToken` can't be empty since the constructor already throws an exception

2024-08-20 20:19 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/vkmusic/VkMusicSourceManager.java
> +			if (reference.identifier.startsWith(SEARCH_PREFIX)) {
ideally put this at the top, regex is way more expensive to check

2024-08-20 20:19 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/vkmusic/VkMusicSourceManager.java
> +			if (reference.identifier.startsWith(RECOMMENDATIONS_PREFIX)) {
ideally put this at the top, regex is way more expensive to check

2024-08-20 20:22 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/vkmusic/VkMusicSourceManager.java
> +			var audioId = json.get("owner_id").text() + "_" + json.get("id").text();
why is the `owner_id` in the id?
are ids not globally unqiue?

2024-08-20 20:27 UTC, Krispeckt commented on main/src/main/java/com/github/topi314/lavasrc/vkmusic/VkMusicSourceManager.java
> +	private static final Pattern VK_PLAYLIST_HEADER_REGEX = Pattern.compile("z=audio_playlist(?<owner>-?[A-Za-z\\d]+)_(?<id>-?[A-Za-z\\d]+)(?<accessKey>_([^/?#]*))?(?:[/?#].*)?");
This is the vk music widget on the page, they have it in the header. The link itself can be different 💀

2024-08-20 20:28 UTC, Krispeckt commented on main/src/main/java/com/github/topi314/lavasrc/vkmusic/VkMusicAudioTrack.java
> +		return new URI(json.get("response").values().get(0).get("url").text());
Only if there's no token

2024-08-20 20:43 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/vkmusic/VkMusicSourceManager.java
> +	private static final Pattern VK_PLAYLIST_HEADER_REGEX = Pattern.compile("z=audio_playlist(?<owner>-?[A-Za-z\\d]+)_(?<id>-?[A-Za-z\\d]+)(?<accessKey>_([^/?#]*))?(?:[/?#].*)?");
i have no idea what this means

2024-08-20 20:44 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/vkmusic/VkMusicAudioTrack.java
> +		return new URI(json.get("response").values().get(0).get("url").text());
then parse it ideally

2024-08-20 20:47 UTC, Krispeckt commented on main/src/main/java/com/github/topi314/lavasrc/vkmusic/VkMusicSourceManager.java
> +	private static final Pattern VK_PLAYLIST_HEADER_REGEX = Pattern.compile("z=audio_playlist(?<owner>-?[A-Za-z\\d]+)_(?<id>-?[A-Za-z\\d]+)(?<accessKey>_([^/?#]*))?(?:[/?#].*)?");
Check out the vk links in the readme

2024-08-20 21:14 UTC, Krispeckt commented on main/src/main/java/com/github/topi314/lavasrc/vkmusic/VkMusicSourceManager.java
> +				throw new RuntimeException(e);
I don't get it

2024-08-20 21:21 UTC, Krispeckt commented on main/src/main/java/com/github/topi314/lavasrc/vkmusic/VkMusicSourceManager.java
> +			var audioId = json.get("owner_id").text() + "_" + json.get("id").text();
This is to create a track ID which consists of owner_id and track_id

2024-08-25 19:56 UTC, topi314 requested changes

2024-08-25 19:56 UTC, topi314 commented on README.md
> +<summary>How to get need user token</summary>
this is not english

2024-08-25 19:56 UTC, topi314 commented on README.md
> +
this is still above flowery tts

2024-08-25 19:56 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/vkmusic/VkMusicAudioTrack.java
> +		}
pretty sure this can't be nil here too

2024-08-25 19:56 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/vkmusic/VkMusicSourceManager.java
> +	private static final Pattern VK_PLAYLIST_HEADER_REGEX = Pattern.compile("z=audio_playlist(?<owner>-?[A-Za-z\\d]+)_(?<id>-?[A-Za-z\\d]+)(?<accessKey>_([^/?#]*))?(?:[/?#].*)?");
ok and how do you load stuff with this regex?

2024-08-25 19:56 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/vkmusic/VkMusicSourceManager.java
> +				throw new RuntimeException(e);
ah the interface has no throws, so this is actually fine

2024-08-25 19:56 UTC, topi314 commented on plugin/src/main/java/com/github/topi314/lavasrc/plugin/LavaSrcPlugin.java
> +	public LavaSrcPlugin(LavaSrcConfig pluginConfig, SourcesConfig sourcesConfig, LyricsSourcesConfig lyricsSourcesConfig, SpotifyConfig spotifyConfig, AppleMusicConfig appleMusicConfig, DeezerConfig de
yet again fix the order to be consistent please

2024-08-25 19:56 UTC, topi314 commented on plugin/src/main/java/com/github/topi314/lavasrc/plugin/LavaSrcPlugin.java
> +	private VkMusicSourceManager vkMusic;
yet again fix the order to be consistent please

2024-08-25 19:56 UTC, topi314 commented on plugin/src/main/java/com/github/topi314/lavasrc/plugin/LavaSrcPlugin.java
> +		}
yet again fix the order to be consistent please

2024-08-25 19:56 UTC, topi314 commented on plugin/src/main/java/com/github/topi314/lavasrc/plugin/LavaSrcPlugin.java
> +		}
yet again fix the order to be consistent please

2024-08-25 19:56 UTC, topi314 commented on plugin/src/main/java/com/github/topi314/lavasrc/plugin/SourcesConfig.java
> +	private boolean vkMusic = false;
yet again fix the order to be consistent please

2024-08-25 19:56 UTC, topi314 commented on plugin/src/main/java/com/github/topi314/lavasrc/plugin/SourcesConfig.java
> +
yet again fix the order to be consistent please

2024-09-06 22:36 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/vkmusic/VkMusicSourceManager.java
> +	private static final Pattern VK_PLAYLIST_HEADER_REGEX = Pattern.compile("z=audio_playlist(?<owner>-?[A-Za-z\\d]+)_(?<id>-?[A-Za-z\\d]+)(?<accessKey>_([^/?#]*))?(?:[/?#].*)?");
this regex makes a lot more sense now, thanks

2024-09-06 22:44 UTC, topi314 requested changes
please resolve conversations when you fixed what I asked there, else I need to check every single one of them myself.

not sure where those spaces come from but there is a `.editorconfig` which should let you simply format lavasrc.

2024-09-06 22:44 UTC, topi314 commented on main/src/main/java/com/github/topi314/lavasrc/vkmusic/VkMusicSourceManager.java
> +			var uri = URLDecoder.decode(reference.identifier, StandardCharsets.UTF_8);
why are you url decoding the url here?
pretty sure it already comes decoded in here, if not this would be a bug in lavalink

2024-09-06 22:44 UTC, topi314 commented on plugin/src/main/java/com/github/topi314/lavasrc/plugin/LyricsSourcesConfig.java
> +		this.yandexMusic = yandexMusic;
this does not seem right

2024-09-06 22:44 UTC, topi314 commented on plugin/src/main/java/com/github/topi314/lavasrc/plugin/VkMusicConfig.java
> +    }
lavasrc uses tabs for indentation

2024-09-06 22:44 UTC, topi314 commented on plugin/src/main/java/com/github/topi314/lavasrc/plugin/LavaSrcPlugin.java
> +            manager.registerLyricsManager(this.vkMusic);
lavasrc uses tabs for indentation

2024-09-06 22:44 UTC, topi314 commented on plugin/src/main/java/com/github/topi314/lavasrc/plugin/LavaSrcPlugin.java
> +            manager.registerSearchManager(this.vkMusic);
lavasrc uses tabs for indentation

2024-09-07 09:46 UTC, Krispeckt commented on plugin/src/main/java/com/github/topi314/lavasrc/plugin/LyricsSourcesConfig.java
> +		this.yandexMusic = yandexMusic;
why, I do not understand

2024-09-15 10:24 UTC, topi314 commented on README.md
> +* [Vk Music](https://music.vk.com/) playlists/albums/songs/artists(top tracks)/search results/[LavaLyrics](https://github.com/topi314/LavaLyrics)/[LavaSearch](https://github.com/topi314/LavaSearch)
```suggestion
* [Vk Music](https://music.vk.com/) playlists/albums/songs/artists(top tracks)/search results/[LavaLyrics](https://github.com/topi314/LavaLyrics)/[LavaSearch](https://github.com/topi314/LavaSearch) (Thx to [Krispeckt](https://github.com/Krispeckt) for implementing it)
```

2024-09-15 10:24 UTC, topi314 commented on README.md
>  * [Yandex Music](https://music.yandex.ru) playlists/albums/songs/artists/podcasts/search results/[LavaLyrics](https://github.com/topi314/LavaLyrics)/[LavaSearch](https://github.com/topi314/LavaSearch
```suggestion
* [Yandex Music](https://music.yandex.ru) playlists/albums/songs/artists/podcasts/search results/[LavaLyrics](https://github.com/topi314/LavaLyrics)/[LavaSearch](https://github.com/topi314/LavaSearch) (Thx to [AgutinVBoy](https://github.com/agutinvboy) for implementing it)
```

2024-09-15 10:25 UTC, topi314 commented on README.md
>  * [Deezer](https://www.deezer.com) playlists/albums/songs/artists/search results/[LavaSearch](https://github.com/topi314/LavaSearch)/[LavaLyrics](https://github.com/topi314/LavaLyrics)(Big thx to [ry
```suggestion
* [Deezer](https://www.deezer.com) playlists/albums/songs/artists/search results/[LavaSearch](https://github.com/topi314/LavaSearch)/[LavaLyrics](https://github.com/topi314/LavaLyrics) (Big thx to [ryan5453](https://github.com/ryan5453) and [melike2d](https://github.com/melike2d) for helping me)
```

2024-09-15 10:25 UTC, topi314 commented on README.md
>  * [Apple Music](https://www.apple.com/apple-music/) playlists/albums/songs/artists/search results/[LavaSearch](https://github.com/topi314/LavaSearch)(Big thx to [ryan5453](https://github.com/ryan5453
```suggestion
* [Apple Music](https://www.apple.com/apple-music/) playlists/albums/songs/artists/search results/[LavaSearch](https://github.com/topi314/LavaSearch) (Big thx to [ryan5453](https://github.com/ryan5453) for helping me)
```

2024-09-15 10:26 UTC, topi314 approved these changes
i think this finally looks acceptable to me

2024-09-15 10:26 UTC, merged

2024-09-15 10:27 UTC, topi314 commented
thanks