Add Flowery TTS as source
topi314/LavaSrc pull request #80
Opened 2023-06-14 21:03 UTC by bachtran02

Add support for Flowery TTS - [Flowery TTS Support #66 ](https://github.com/topi314/LavaSrc/issues/66)

2023-06-14 21:17 UTC, topi314 requested changes

2023-06-14 21:17 UTC, topi314 commented on plugin/src/main/java/com/github/topisenpai/lavasrc/plugin/LavaSrcPlugin.java
> +		if (this.sourcesConfig.isFloweryTTS()) {
can you please validate this in the constructor and not here?

2023-06-14 21:17 UTC, topi314 commented on main/src/main/java/com/github/topisenpai/lavasrc/flowerytts/FloweryTTSSourceManager.java
> +                            "text-to-speech",
the track title should make sense, and not be a static string

2023-06-14 21:17 UTC, topi314 commented on main/src/main/java/com/github/topisenpai/lavasrc/flowerytts/FloweryTTSSourceManager.java
> +                            "no-id",
the identifier should be unique per track

2023-07-02 02:12 UTC, bachtran02 commented on main/src/main/java/com/github/topisenpai/lavasrc/flowerytts/FloweryTTSSourceManager.java
> +                            "no-id",
fixed in latest commit

2023-07-02 02:12 UTC, bachtran02 commented on main/src/main/java/com/github/topisenpai/lavasrc/flowerytts/FloweryTTSSourceManager.java
> +                            "text-to-speech",
fixed in latest commit

2023-07-02 02:12 UTC, bachtran02 commented on plugin/src/main/java/com/github/topisenpai/lavasrc/plugin/LavaSrcPlugin.java
> +		if (this.sourcesConfig.isFloweryTTS()) {
fixed in latest commit

2023-07-02 09:21 UTC, topi314 requested changes

2023-07-02 09:21 UTC, topi314 commented on application.yml.example
> +    flowerytts:
```suggestion
    flowery_tts:
```

2023-07-02 09:21 UTC, topi314 commented on main/src/main/java/com/github/topisenpai/lavasrc/flowerytts/FloweryTTSSourceManager.java
> +                e.printStackTrace();
```suggestion
                throw new RuntimeException(e);

```

2023-07-02 09:21 UTC, topi314 commented on plugin/src/main/java/com/github/topisenpai/lavasrc/plugin/FloweryTTSConfig.java
> +    private final float SPEED_MAX = 10;
```suggestion
    private static final int SILENCE_MIN = 0;
    private static final int SILENCE_MAX = 10000;
    private static final float SPEED_MIN = 0.5f;
    private static final float SPEED_MAX = 10;

```

2023-07-02 09:21 UTC, topi314 commented on plugin/src/main/java/com/github/topisenpai/lavasrc/plugin/FloweryTTSConfig.java
> +        this.silence = silence > SILENCE_MAX ? SILENCE_MAX : silence < SILENCE_MIN ? SILENCE_MIN : silence;
please use `Math.min` & `Math.max`

2023-07-02 09:21 UTC, topi314 commented on plugin/src/main/java/com/github/topisenpai/lavasrc/plugin/FloweryTTSConfig.java
> +        this.speed = speed > SPEED_MAX ? SPEED_MAX : speed < SPEED_MIN ? SPEED_MIN : speed;
please use `Math.min` & `Math.max`

2023-07-02 09:21 UTC, topi314 commented on plugin/src/main/java/com/github/topisenpai/lavasrc/plugin/LavaSrcPlugin.java
> +			if (this.floweryTTSConfig.getTranslate() == true){
```suggestion
			if (this.floweryTTSConfig.getTranslate()){
```

2023-07-02 09:21 UTC, topi314 commented on plugin/src/main/java/com/github/topisenpai/lavasrc/plugin/FloweryTTSConfig.java
> +@ConfigurationProperties(prefix = "plugins.lavasrc.flowerytts")
```suggestion
@ConfigurationProperties(prefix = "plugins.lavasrc.flowery_tts")

```

2023-07-02 09:21 UTC, topi314 commented on main/src/main/java/com/github/topisenpai/lavasrc/flowerytts/FloweryTTSSourceManager.java
> +                        queryUri.getAuthority(),
this should be `tts://bla?key=value`, just assemble the api url once you acutally need it

2023-07-02 09:21 UTC, topi314 commented on main/src/main/java/com/github/topisenpai/lavasrc/flowerytts/FloweryTTSSourceManager.java
> +    public FloweryTTSSourceManager(String voice) {
lets use a default voice too & remove the voice param

2023-07-03 23:41 UTC, closed without merging